version: "3"
services:
  botdiscord:
    image: bot_discord
    depends_on:
      - serveurai
    ports:
      - "80:80"
    networks:
      - networkName
  serveurai:
    image: backend_ai
    ports:
      - "5000:5000"
    networks:
      - networkName


networks:
  networkName:
